import { useState, useEffect } from "react";
import { AreaChart, Area, LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine } from "recharts";

const SUPABASE_URL = "https://cupcsspfmkgbcovtgszm.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1cGNzc3BmbWtnYmNvdnRnc3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyNzI4ODMsImV4cCI6MjA5NDg0ODg4M30.Y8o09mcvdJuSSfgsVGnhoUyRpIUPVl8-gkigJXXee8E";
const HEADERS = { apikey: SUPABASE_KEY, Authorization: "Bearer " + SUPABASE_KEY };
const COMMODITIES = [{ id: "corn", label: "Corn" }, { id: "wheat", label: "Wheat" }, { id: "soybeans", label: "Soybeans" }];

function fmt(n, d) { if (d === undefined) d = 2; return Number(n).toFixed(d); }
function fmtK(n) { return n >= 1000 ? (n / 1000).toFixed(1) + "k" : fmt(n); }
function calcMA(prices, period) { return prices.map(function(_, i) { if (i < period - 1) return null; var s = prices.slice(i - period + 1, i + 1); return s.reduce(function(a, b) { return a + b; }, 0) / period; }); }
function calcRSI(prices, period) { if (!period) period = 14; var rsi = new Array(prices.length).fill(null); for (var i = period; i < prices.length; i++) { var g = 0, l = 0; for (var j = i - period + 1; j <= i; j++) { var d = prices[j] - prices[j-1]; if (d > 0) g += d; else l -= d; } var ag = g/period, al = l/period; rsi[i] = al === 0 ? 100 : 100 - (100 / (1 + ag/al)); } return rsi; }
function calcBollinger(prices, period, mult) { if (!period) period = 20; if (!mult) mult = 2; return prices.map(function(_, i) { if (i < period - 1) return { upper: null, lower: null }; var s = prices.slice(i - period + 1, i + 1); var mean = s.reduce(function(a,b){return a+b;},0)/period; var std = Math.sqrt(s.reduce(function(a,b){return a+Math.pow(b-mean,2);},0)/period); return { upper: mean + mult*std, lower: mean - mult*std }; }); }
function calcEMA(prices, period) { var k = 2/(period+1), ema = new Array(prices.length).fill(null), fv = -1; for (var i = 0; i < prices.length; i++) { if (prices[i] !== null) { fv = i; break; } } if (fv === -1) return ema; ema[fv] = prices[fv]; for (var i = fv+1; i < prices.length; i++) ema[i] = prices[i] === null ? ema[i-1] : prices[i]*k + ema[i-1]*(1-k); return ema; }
function calcMACD(prices) { var e12=calcEMA(prices,12), e26=calcEMA(prices,26); var ml=prices.map(function(_,i){return (e12[i]===null||e26[i]===null)?null:e12[i]-e26[i];}); var sl=calcEMA(ml.filter(function(v){return v!==null;}),9); var res=new Array(prices.length).fill(null), ni=0; ml.forEach(function(v,i){ if(v!==null){res[i]={macd:v,signal:sl[ni]||null,histogram:sl[ni]!==null?v-sl[ni]:null};ni++;} else res[i]={macd:null,signal:null,histogram:null}; }); return res; }
function calcSR(prices) { var s=prices.slice().sort(function(a,b){return a-b;}); return {support:s[Math.floor(s.length*0.1)],resistance:s[Math.floor(s.length*0.9)]}; }
function calcZScore(prices) { var mean=prices.reduce(function(a,b){return a+b;},0)/prices.length; var std=Math.sqrt(prices.reduce(function(a,b){return a+Math.pow(b-mean,2);},0)/prices.length); return std===0?0:(prices[prices.length-1]-mean)/std; }
function getTrend(prices) { if(prices.length<5)return "neutral"; var r=prices.slice(-5), pct=(r[r.length-1]-r[0])/r[0]*100; return pct>1?"bullish":pct<-1?"bearish":"neutral"; }
function TT(props) { var active=props.active, payload=props.payload, label=props.label; if(!active||!payload||!payload.length)return null; return (<div style={{background:"#1a2035",border:"1px solid #2a3550",borderRadius:10,padding:"10px 14px",fontSize:11,boxShadow:"0 8px 24px rgba(0,0,0,0.4)"}}><p style={{color:"#7b8db0",marginBottom:5,fontWeight:600}}>{label}</p>{payload.map(function(p,i){if(p.value===null||p.value===undefined)return null;return <p key={i} style={{color:p.color,margin:"2px 0"}}>{p.name}: <strong>{typeof p.value==="number"?p.value.toFixed(2):p.value}</strong></p>;})}</div>); }

export default function App() {
  var [commodity,setCommodity]=useState("corn");
  var [data,setData]=useState([]);
  var [loading,setLoading]=useState(true);
  var [tab,setTab]=useState("overview");
  var [updated,setUpdated]=useState(null);
  var [ai,setAi]=useState("");
  var [aiLoad,setAiLoad]=useState(false);
  var [weekly,setWeekly]=useState([]);
  var [news,setNews]=useState([]);
  var [newsLoad,setNewsLoad]=useState(false);
  var C={bg:"#111827",sb:"#0f172a",card:"#1a2035",border:"#2a3550",text:"#f1f5f9",sub:"#7b8db0",muted:"#3d4f6e",blue:"#4f8ef7",purple:"#9d7cf8",green:"#34d399",red:"#f87171",amber:"#fbbf24",cyan:"#22d3ee",pink:"#f472b6"};

  function GCard(props){var label=props.label,value=props.value,unit=props.unit,gradient=props.gradient,delta=props.delta,pct=props.pct,mape=props.mape;var dc=delta===undefined?null:delta>0?C.green:delta<0?C.red:C.sub;return(<div style={{background:gradient||C.card,borderRadius:16,padding:"20px 22px",color:"#fff",position:"relative",overflow:"hidden",boxShadow:"0 4px 24px rgba(0,0,0,0.3)"}}><div style={{position:"absolute",top:-30,right:-30,width:100,height:100,borderRadius:"50%",background:"rgba(255,255,255,0.06)"}}/><div style={{fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.12em",opacity:0.8,marginBottom:8}}>{label}</div><div style={{fontSize:28,fontWeight:900,lineHeight:1,marginBottom:4}}>{value}</div><div style={{fontSize:11,opacity:0.7}}>{unit}</div>{dc&&delta!==undefined&&<div style={{marginTop:8,fontSize:12,fontWeight:700,background:"rgba(255,255,255,0.15)",borderRadius:6,padding:"2px 8px",display:"inline-block"}}>{delta>0?"+":"-"}{fmt(Math.abs(delta))}{pct!==undefined?" ("+fmt(Math.abs(pct))+"%)":""}</div>}{mape!==undefined&&<div style={{marginTop:8,fontSize:11,opacity:0.85}}>MAPE: {mape!==null?mape.toFixed(2)+"%":"accumulating..."}</div>}</div>);}
  function FCard(props){var label=props.label,value=props.value,unit=props.unit,color=props.color,delta=props.delta,pct=props.pct,mape=props.mape;var dc=delta===undefined?C.sub:delta>0?C.green:delta<0?C.red:C.sub;return(<div style={{background:C.card,border:"1px solid "+C.border,borderRadius:14,padding:"16px 18px",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,left:0,right:0,height:"2px",background:color}}/><div style={{fontSize:10,fontWeight:700,color:C.sub,textTransform:"uppercase",letterSpacing:"0.1em",marginBottom:8}}>{label}</div><div style={{fontSize:22,fontWeight:800,color:C.text,lineHeight:1,marginBottom:4}}>{value}</div><div style={{fontSize:11,color:C.muted}}>{unit}</div>{delta!==undefined&&<div style={{marginTop:6,fontSize:11,fontWeight:700,color:dc}}>{delta>0?"+":delta<0?"-":""}{fmt(Math.abs(delta))}{pct!==undefined?" ("+fmt(Math.abs(pct))+"%)":""}</div>}{mape!==undefined&&<div style={{marginTop:6,fontSize:10,color:mape!==null?(mape<2?C.green:mape<5?C.amber:C.red):C.muted}}>MAPE: {mape!==null?mape.toFixed(2)+"%":"accumulating..."}</div>}</div>);}

  function loadNews(){
    setNewsLoad(true);
    var apiKey = "b00e23b7c540f21999457d10e097d21f";
    var newsUrl = "https://gnews.io/api/v4/search?q=corn+futures+CBOT&lang=en&max=10&token=" + apiKey;
    var proxy = "https://corsproxy.io/?" + encodeURIComponent(newsUrl);
    fetch(proxy)
      .then(function(r){return r.json();})
      .then(function(data){
        if(data.articles) setNews(data.articles.map(function(a){
          return {
            title: a.title,
            link: a.url,
            pubDate: a.publishedAt,
            source: a.source ? a.source.name : "News"
          };
        }));
        setNewsLoad(false);
      })
      .catch(function(e){console.error("News error:",e);setNewsLoad(false);});
  }

  function loadData(c){setLoading(true);fetch(SUPABASE_URL+"/rest/v1/commodity_prices?commodity=eq."+c+"&order=date.desc&limit=60",{headers:HEADERS}).then(function(r){return r.json();}).then(function(rows){setData(rows);setUpdated(new Date());setLoading(false);}).catch(function(e){console.error(e);setLoading(false);});}
  function loadWeekly(c){fetch(SUPABASE_URL+"/rest/v1/weekly_forecast?commodity=eq."+c+"&order=forecast_date.asc&limit=10",{headers:HEADERS}).then(function(r){return r.json();}).then(function(rows){setWeekly(rows);}).catch(function(e){console.error(e);});}
  useEffect(function(){loadData(commodity);loadWeekly(commodity);var iv=setInterval(function(){loadData(commodity);},5*60*1000);return function(){clearInterval(iv);};},[commodity]);

  var L=data[0],P=data[1];
  var cbotD=L&&P?L.closing_cbot-P.closing_cbot:0,cbotPct=P&&P.closing_cbot?(cbotD/P.closing_cbot)*100:0,argD=L&&P?L.arg_price-P.arg_price:0;
  var prices=data.slice().reverse().map(function(d){return d.closing_cbot;}),dates=data.slice().reverse().map(function(d){return d.date?d.date.slice(5):"";});
  var ma7=calcMA(prices,7),ma21=calcMA(prices,21),rsiA=calcRSI(prices,14),bollA=calcBollinger(prices,20,2),macdA=calcMACD(prices);
  var sr=calcSR(prices),zs=calcZScore(prices),trend=getTrend(prices);
  var rsi=rsiA[rsiA.length-1],macd=macdA[macdA.length-1],boll=bollA[bollA.length-1];
  var rsiSig=rsi!==null?(rsi<30?"BUY":rsi>70?"SELL":"HOLD"):"HOLD";
  var macdSig=macd&&macd.macd!==null&&macd.signal!==null?(macd.macd>macd.signal?"BUY":"SELL"):"HOLD";
  var trendSig=trend==="bullish"?"BUY":trend==="bearish"?"SELL":"HOLD";
  var buys=[rsiSig,macdSig,trendSig].filter(function(s){return s==="BUY";}).length;
  var sells=[rsiSig,macdSig,trendSig].filter(function(s){return s==="SELL";}).length;
  var sig=buys>=2?"BUY":sells>=2?"SELL":"HOLD";
  var sigC=sig==="BUY"?C.green:sig==="SELL"?C.red:C.amber;
  var tC=trend==="bullish"?C.green:trend==="bearish"?C.red:C.amber;
  var cd=dates.map(function(date,i){return{date:date,close:prices[i]!==undefined?parseFloat(prices[i].toFixed(2)):null,ma7:ma7[i]!==null?parseFloat(ma7[i].toFixed(2)):null,ma21:ma21[i]!==null?parseFloat(ma21[i].toFixed(2)):null,upper:bollA[i].upper!==null?parseFloat(bollA[i].upper.toFixed(2)):null,lower:bollA[i].lower!==null?parseFloat(bollA[i].lower.toFixed(2)):null,rsi:rsiA[i]!==null?parseFloat(rsiA[i].toFixed(2)):null,histogram:macdA[i].histogram!==null?parseFloat(macdA[i].histogram.toFixed(4)):null,ret:data[data.length-1-i]&&data[data.length-1-i].fut_ret?parseFloat((data[data.length-1-i].fut_ret*100).toFixed(2)):null};});

  function runAI(){setAiLoad(true);setAi("");setTab("analysis");setTimeout(function(){setAi(report());setAiLoad(false);},800);}
  function report(){if(!L||prices.length<5)return "Not enough data.";var lines=[],c=L.closing_cbot,p5=prices.slice(-6,-1),pct5=((c-p5[0])/p5[0]*100);lines.push("PRICE SUMMARY — "+L.date);lines.push("─────────────────────────");if(cbotD>0)lines.push("UP "+Math.abs(cbotD).toFixed(2)+" ("+Math.abs(cbotPct).toFixed(2)+"%) — "+c.toFixed(2)+" ¢/bu");else if(cbotD<0)lines.push("DOWN "+Math.abs(cbotD).toFixed(2)+" ("+Math.abs(cbotPct).toFixed(2)+"%) — "+c.toFixed(2)+" ¢/bu");else lines.push("FLAT — "+c.toFixed(2)+" ¢/bu");lines.push("5-session: "+(pct5>=0?"+":"")+pct5.toFixed(2)+"%");lines.push("");lines.push("TECHNICAL INDICATORS");lines.push("─────────────────────────");if(rsi!==null){var r="RSI(14) = "+rsi.toFixed(1)+" — ";if(rsi<30)r+="OVERSOLD";else if(rsi<45)r+="Bearish";else if(rsi<55)r+="Neutral";else if(rsi<70)r+="Bullish";else r+="OVERBOUGHT";lines.push(r);}if(macd&&macd.histogram!==null)lines.push("MACD = "+macd.histogram.toFixed(4)+" — "+(macd.histogram>0?"Bullish":"Bearish"));lines.push("Z-Score = "+zs.toFixed(2)+(Math.abs(zs)>2?" EXTREME!":""));var m7=ma7[ma7.length-1],m21=ma21[ma21.length-1];if(m7&&m21)lines.push("MA7="+m7.toFixed(2)+" MA21="+m21.toFixed(2)+" — "+(m7>m21?"Bullish":"Bearish"));lines.push("");lines.push("KEY LEVELS");lines.push("─────────────────────────");lines.push("Support: "+sr.support.toFixed(2)+" | Resistance: "+sr.resistance.toFixed(2));lines.push("");lines.push("LOCAL (EGP)");lines.push("─────────────────────────");lines.push("Dollar: "+L.dollar_rate.toFixed(2)+" | "+(isWheat?"11.5%":"ARG")+": "+Math.round(L.arg_price).toLocaleString()+" | "+(isWheat?"12.5%":"BRZ")+": "+Math.round(L.brz_price).toLocaleString());lines.push("");lines.push("SIGNAL: "+sig+" ("+buys+"B/"+sells+"S)");if(sig==="BUY")lines.push("Bullish. Watch R: "+sr.resistance.toFixed(2));else if(sig==="SELL")lines.push("Bearish. Watch S: "+sr.support.toFixed(2));else lines.push("Mixed. Wait for breakout.");return lines.join("\n");}

  var cc=COMMODITIES.find(function(c){return c.id===commodity;});
  var isWheat = commodity === "wheat";
  var label1 = isWheat ? "11.5% Price" : "ARG Local Price";
  var label2 = isWheat ? "12.5% Price" : "BRZ Price";
  var label3 = isWheat ? "11.5% Forecast" : "ARG Forecast";
  var label4 = isWheat ? "12.5% Forecast" : "BRZ Forecast";
  var nav=[["overview","Overview"],["charts","Charts"],["analysis","AI Analysis"],["returns","Returns"],["table","Raw Data"],["weekly","Weekly Forecast"],["news","Market News"]];

  return(
    <div style={{minHeight:"100vh",background:C.bg,color:C.text,fontFamily:"'Inter','DM Sans','Segoe UI',sans-serif",display:"flex"}}>
      <div style={{width:230,minHeight:"100vh",background:C.sb,display:"flex",flexDirection:"column",position:"fixed",top:0,left:0,bottom:0,overflowY:"auto",borderRight:"1px solid "+C.border}}>
        <div style={{padding:"22px 20px 18px",borderBottom:"1px solid "+C.border}}><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:36,height:36,borderRadius:10,background:"linear-gradient(135deg,"+C.blue+","+C.purple+")",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,fontSize:14,color:"#fff",boxShadow:"0 4px 12px rgba(79,142,247,0.4)"}}>AM</div><div><div style={{fontSize:14,fontWeight:800,color:C.text}}>AdmMedSofts</div><div style={{fontSize:10,color:C.sub}}>Commodity Intelligence</div></div></div></div>
        <div style={{padding:"18px 14px 8px"}}><div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:"uppercase",letterSpacing:"0.14em",marginBottom:10,paddingLeft:6}}>Markets</div>{COMMODITIES.map(function(c){var active=commodity===c.id;return(<button key={c.id} onClick={function(){setCommodity(c.id);}} style={{width:"100%",display:"flex",alignItems:"center",justifyContent:"space-between",padding:"7px 12px",borderRadius:8,border:"none",cursor:"pointer",marginBottom:2,background:active?"linear-gradient(135deg,rgba(79,142,247,0.2),rgba(157,124,248,0.1))":"transparent",color:active?C.blue:C.sub,fontWeight:active?700:400,fontSize:13,textAlign:"left",borderLeft:active?"3px solid "+C.blue:"3px solid transparent"}}><span>{c.label}</span>{c.id!=="corn"&&<span style={{fontSize:9,color:C.muted,border:"1px solid "+C.border,padding:"1px 7px",borderRadius:5}}>Soon</span>}</button>);})}</div>
        <div style={{padding:"8px 14px"}}><div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:"uppercase",letterSpacing:"0.14em",marginBottom:10,paddingLeft:6}}>Views</div>{nav.map(function(item){var id=item[0],label=item[1],active=tab===id;return(<button key={id} onClick={function(){setTab(id);}} style={{width:"100%",padding:"7px 12px",borderRadius:8,border:"none",cursor:"pointer",marginBottom:2,background:active?"linear-gradient(135deg,rgba(79,142,247,0.2),rgba(157,124,248,0.1))":"transparent",color:active?C.blue:C.sub,fontWeight:active?700:400,fontSize:13,textAlign:"left",borderLeft:active?"3px solid "+C.blue:"3px solid transparent"}}>{label}</button>);})}</div>
        <div style={{marginTop:"auto",padding:"14px 14px 20px",borderTop:"1px solid "+C.border}}><button onClick={function(){loadData(commodity);loadWeekly(commodity);}} style={{width:"100%",padding:"9px 12px",borderRadius:10,border:"1px solid "+C.border,background:"transparent",color:C.sub,fontSize:11,cursor:"pointer",marginBottom:10,textAlign:"left",fontWeight:500}}>Refresh Data</button><button onClick={runAI} style={{width:"100%",padding:"9px 12px",borderRadius:10,border:"none",background:"linear-gradient(135deg,"+C.blue+","+C.purple+")",color:"#fff",fontSize:12,cursor:"pointer",fontWeight:700,boxShadow:"0 4px 16px rgba(79,142,247,0.35)"}}>Run AI Analysis</button>{updated&&<div style={{fontSize:9,color:C.muted,marginTop:10,textAlign:"center"}}>Updated {updated.toLocaleTimeString()}</div>}</div>
      </div>
      <div style={{marginLeft:230,flex:1,padding:"28px 32px",minWidth:0}}>
        <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:28}}><div><h1 style={{fontSize:24,fontWeight:900,margin:0,color:C.text,letterSpacing:"-0.5px"}}>{cc?cc.label:""} Market</h1><div style={{fontSize:12,color:C.sub,marginTop:4}}>CBOT Futures · EGP Local Prices · {L?L.date:"—"}</div></div><div style={{display:"flex",gap:10}}>{Math.abs(cbotPct)>=2&&<div style={{background:"rgba(248,113,113,0.12)",border:"1px solid rgba(248,113,113,0.3)",borderRadius:10,padding:"7px 14px",fontSize:12,color:C.red,fontWeight:700}}>{fmt(Math.abs(cbotPct))}% move</div>}<div style={{background:C.card,border:"1px solid "+C.border,borderRadius:10,padding:"7px 14px",fontSize:12,color:C.sub}}>{data.length} pts</div><div style={{background:trend==="bullish"?"rgba(52,211,153,0.12)":trend==="bearish"?"rgba(248,113,113,0.12)":"rgba(251,191,36,0.12)",border:"1px solid "+(trend==="bullish"?"rgba(52,211,153,0.3)":trend==="bearish"?"rgba(248,113,113,0.3)":"rgba(251,191,36,0.3)"),borderRadius:10,padding:"7px 14px",fontSize:12,color:tC,fontWeight:700}}>{trend==="bullish"?"Bullish":trend==="bearish"?"Bearish":"Neutral"}</div></div></div>
        {loading?(<div style={{display:"flex",alignItems:"center",justifyContent:"center",height:300,color:C.sub}}>Loading...</div>):!L?(<div style={{textAlign:"center",padding:80,color:C.sub}}>No data</div>):(
          <div>
            {(tab==="overview"||tab==="charts"||tab==="analysis")&&(<div style={{marginBottom:20}}><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14,marginBottom:14}}><GCard label="CBOT Close" value={fmt(L.closing_cbot)} unit="cents / bushel" gradient={"linear-gradient(135deg,"+C.blue+","+C.purple+")"} delta={cbotD} pct={cbotPct}/><GCard label={label1} value={fmtK(L.arg_price)} unit="Egyptian Pound" gradient={"linear-gradient(135deg,"+C.green+",#059669)"} delta={argD}/><GCard label={label2} value={fmtK(L.brz_price)} unit="Egyptian Pound" gradient={"linear-gradient(135deg,"+C.amber+",#d97706)"}/><GCard label="Dollar Rate" value={fmt(L.dollar_rate)} unit="EGP / USD" gradient={"linear-gradient(135deg,"+C.pink+","+C.purple+")"}/>
            </div><div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:12,marginBottom:14}}>{[
                    {label:"Open",value:fmt(L.cbot_open),color:C.sub},
                    {label:"High",value:fmt(L.cbot_high),color:C.green},
                    {label:"Low",value:fmt(L.cbot_low),color:C.red},
                    {label:"Close",value:fmt(L.closing_cbot),color:C.blue},
                    {label:"CBOT Forecast",value:L.cbot_predicted?fmt(L.cbot_predicted):"—",color:C.purple,mape:L.mape_cbot},
                    {label:"ARG Forecast",value:L.arg_predicted?fmtK(L.arg_predicted):"—",color:C.green,mape:L.mape_arg},
                    {label:"BRZ Forecast",value:L.brz_predicted?fmtK(L.brz_predicted):"—",color:C.amber,mape:L.mape_brz},
                  ].map(function(item,i){return(
                    <div key={i} style={{background:C.card,border:"1px solid "+C.border,borderRadius:12,padding:"14px 16px",borderTop:"2px solid "+item.color}}>
                      <div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:"uppercase",letterSpacing:"0.1em",marginBottom:6}}>{item.label}</div>
                      <div style={{fontSize:18,fontWeight:800,color:item.color,fontVariantNumeric:"tabular-nums"}}>{item.value}</div>
                      {item.mape!==undefined&&<div style={{fontSize:10,color:item.mape!==null?(item.mape<2?C.green:item.mape<5?C.amber:C.red):C.muted,marginTop:4}}>MAPE: {item.mape!==null?item.mape.toFixed(2)+"%":"accumulating..."}</div>}
                    </div>
                  );})}</div></div>)}
            {tab==="overview"&&(<div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:16}}><div style={{background:C.card,border:"1px solid "+C.border,borderRadius:16,padding:"20px 22px 14px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><div style={{fontSize:13,fontWeight:700,color:C.text}}>CBOT Price Trend</div><div style={{display:"flex",gap:14,fontSize:11,color:C.sub}}><span><span style={{display:"inline-block",width:12,height:2,background:C.blue,borderRadius:2,marginRight:5,verticalAlign:"middle"}}></span>Close</span><span><span style={{display:"inline-block",width:12,height:2,background:C.amber,borderRadius:2,marginRight:5,verticalAlign:"middle"}}></span>MA7</span><span><span style={{display:"inline-block",width:12,height:2,background:C.purple,borderRadius:2,marginRight:5,verticalAlign:"middle"}}></span>MA21</span></div></div><ResponsiveContainer width="100%" height={230}><AreaChart data={cd}><defs><linearGradient id="bg1" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.blue} stopOpacity={0.2}/><stop offset="95%" stopColor={C.blue} stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke={C.border}/><XAxis dataKey="date" tick={{fill:C.sub,fontSize:10}}/><YAxis tick={{fill:C.sub,fontSize:10}} domain={["auto","auto"]}/><Tooltip content={<TT/>}/><Area type="monotone" dataKey="close" stroke={C.blue} strokeWidth={2.5} fill="url(#bg1)" dot={false} name="Close"/><Line type="monotone" dataKey="ma7" stroke={C.amber} strokeWidth={1.5} dot={false} name="MA7" strokeDasharray="5 3"/><Line type="monotone" dataKey="ma21" stroke={C.purple} strokeWidth={1.5} dot={false} name="MA21" strokeDasharray="5 3"/></AreaChart></ResponsiveContainer></div><div style={{display:"flex",flexDirection:"column",gap:10}}>{[{label:"Overall Signal",value:sig,color:sigC,sub:buys+" buy / "+sells+" sell"},{label:"RSI (14)",value:rsi?rsi.toFixed(1):"—",color:rsi?(rsi<30?C.green:rsi>70?C.red:C.amber):C.amber,sub:rsi?(rsi<30?"Oversold":rsi>70?"Overbought":"Neutral"):""},{label:"Z-Score",value:zs.toFixed(2),color:Math.abs(zs)>2?C.red:C.cyan,sub:Math.abs(zs)>2?"Extreme":"Normal"},{label:"Support",value:fmt(sr.support),color:C.green,sub:"cents/bu floor"},{label:"Resistance",value:fmt(sr.resistance),color:C.red,sub:"cents/bu ceiling"}].map(function(item,i){return(<div key={i} style={{background:C.card,border:"1px solid "+C.border,borderRadius:12,padding:"12px 16px",flex:1}}><div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:"uppercase",letterSpacing:"0.1em"}}>{item.label}</div><div style={{fontSize:20,fontWeight:800,color:item.color,marginTop:3}}>{item.value}</div><div style={{fontSize:10,color:C.sub}}>{item.sub}</div></div>);})}</div></div>)}
            {tab==="charts"&&(<div style={{display:"flex",flexDirection:"column",gap:16}}><div style={{background:C.card,border:"1px solid "+C.border,borderRadius:16,padding:"20px 22px 14px"}}><div style={{fontSize:13,fontWeight:700,color:C.text,marginBottom:16}}>Price + Bollinger Bands</div><ResponsiveContainer width="100%" height={250}><LineChart data={cd}><CartesianGrid strokeDasharray="3 3" stroke={C.border}/><XAxis dataKey="date" tick={{fill:C.sub,fontSize:10}}/><YAxis tick={{fill:C.sub,fontSize:10}} domain={["auto","auto"]}/><Tooltip content={<TT/>}/><Line type="monotone" dataKey="upper" stroke={C.cyan} strokeWidth={1} dot={false} name="BB Upper" strokeDasharray="3 3"/><Line type="monotone" dataKey="close" stroke={C.blue} strokeWidth={2.5} dot={false} name="Close"/><Line type="monotone" dataKey="lower" stroke={C.red} strokeWidth={1} dot={false} name="BB Lower" strokeDasharray="3 3"/><ReferenceLine y={sr.support} stroke={C.green} strokeDasharray="5 5" label={{value:"S",fill:C.green,fontSize:9}}/><ReferenceLine y={sr.resistance} stroke={C.red} strokeDasharray="5 5" label={{value:"R",fill:C.red,fontSize:9}}/></LineChart></ResponsiveContainer></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}><div style={{background:C.card,border:"1px solid "+C.border,borderRadius:16,padding:"20px 22px 14px"}}><div style={{fontSize:13,fontWeight:700,color:C.text,marginBottom:14}}>RSI (14)</div><ResponsiveContainer width="100%" height={170}><AreaChart data={cd}><defs><linearGradient id="rg" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.amber} stopOpacity={0.2}/><stop offset="95%" stopColor={C.amber} stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke={C.border}/><XAxis dataKey="date" tick={{fill:C.sub,fontSize:9}}/><YAxis domain={[0,100]} tick={{fill:C.sub,fontSize:9}}/><Tooltip content={<TT/>}/><ReferenceLine y={70} stroke={C.red} strokeDasharray="4 4"/><ReferenceLine y={30} stroke={C.green} strokeDasharray="4 4"/><Area type="monotone" dataKey="rsi" stroke={C.amber} strokeWidth={2} fill="url(#rg)" dot={false} name="RSI"/></AreaChart></ResponsiveContainer></div><div style={{background:C.card,border:"1px solid "+C.border,borderRadius:16,padding:"20px 22px 14px"}}><div style={{fontSize:13,fontWeight:700,color:C.text,marginBottom:14}}>MACD</div><ResponsiveContainer width="100%" height={170}><BarChart data={cd}><CartesianGrid strokeDasharray="3 3" stroke={C.border}/><XAxis dataKey="date" tick={{fill:C.sub,fontSize:9}}/><YAxis tick={{fill:C.sub,fontSize:9}}/><Tooltip content={<TT/>}/><ReferenceLine y={0} stroke={C.border} strokeWidth={2}/><Bar dataKey="histogram" name="MACD" fill={C.purple} radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div></div></div>)}
            {tab==="analysis"&&(<div style={{display:"flex",flexDirection:"column",gap:14}}><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}>{[{label:"Overall",value:sig,color:sigC,sub:buys+"B/"+sells+"S"},{label:"RSI Signal",value:rsiSig,color:rsiSig==="BUY"?C.green:rsiSig==="SELL"?C.red:C.amber,sub:"RSI="+(rsi?rsi.toFixed(1):"—")},{label:"MACD Signal",value:macdSig,color:macdSig==="BUY"?C.green:macdSig==="SELL"?C.red:C.amber,sub:macd&&macd.histogram?(macd.histogram>0?"Mom+":"Mom-"):"—"},{label:"Trend",value:trendSig,color:trendSig==="BUY"?C.green:trendSig==="SELL"?C.red:C.amber,sub:trend}].map(function(c,i){return(<div key={i} style={{background:C.card,border:"1px solid "+C.border,borderRadius:14,padding:"18px 20px",textAlign:"center"}}><div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:"uppercase",letterSpacing:"0.1em",marginBottom:12}}>{c.label}</div><div style={{fontSize:18,fontWeight:800,color:c.color,border:"1px solid "+c.color+"50",display:"inline-block",padding:"4px 16px",borderRadius:8,marginBottom:8}}>{c.value}</div><div style={{fontSize:11,color:C.sub}}>{c.sub}</div></div>);})}</div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}>{[{label:"Z-Score",value:zs.toFixed(2),color:Math.abs(zs)>2?C.red:C.cyan,sub:Math.abs(zs)>2?"Extreme":"Normal"},{label:"Support",value:fmt(sr.support),color:C.green,sub:"floor"},{label:"Resistance",value:fmt(sr.resistance),color:C.red,sub:"ceiling"},{label:"Bollinger",value:boll&&boll.upper?(L.closing_cbot>boll.upper?"Above":L.closing_cbot<boll.lower?"Below":"Inside"):"—",color:C.purple,sub:boll&&boll.upper?"U:"+fmt(boll.upper):""}].map(function(c,i){return(<div key={i} style={{background:C.card,border:"1px solid "+C.border,borderRadius:14,padding:"16px 18px"}}><div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:"uppercase",letterSpacing:"0.1em",marginBottom:8}}>{c.label}</div><div style={{fontSize:20,fontWeight:800,color:c.color}}>{c.value}</div><div style={{fontSize:11,color:C.sub}}>{c.sub}</div></div>);})}</div><div style={{background:C.card,border:"1px solid "+C.border,borderRadius:16,padding:"20px 24px"}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:16}}><div style={{fontSize:14,fontWeight:700,color:C.text}}>AI Market Analysis</div><button onClick={runAI} style={{padding:"7px 16px",borderRadius:10,border:"1px solid "+C.border,background:"transparent",color:C.sub,fontSize:11,cursor:"pointer",fontWeight:600}}>{aiLoad?"Analyzing...":"Refresh"}</button></div>{aiLoad?(<div style={{color:C.sub,fontSize:12,padding:"20px 0",textAlign:"center"}}>Scanning...</div>):ai?(<div style={{color:C.text,fontSize:12,lineHeight:1.9,whiteSpace:"pre-wrap",fontFamily:"monospace"}}>{ai}</div>):(<div style={{color:C.sub,fontSize:13,textAlign:"center",padding:"24px 0"}}>Click "Run AI Analysis" to generate a market report.</div>)}</div></div>)}
            {tab==="returns"&&(<div style={{background:C.card,border:"1px solid "+C.border,borderRadius:16,padding:"20px 22px 14px"}}><div style={{fontSize:13,fontWeight:700,color:C.text,marginBottom:16}}>Daily Futures Returns (%)</div><ResponsiveContainer width="100%" height={300}><BarChart data={cd}><CartesianGrid strokeDasharray="3 3" stroke={C.border}/><XAxis dataKey="date" tick={{fill:C.sub,fontSize:10}}/><YAxis tick={{fill:C.sub,fontSize:10}} tickFormatter={function(v){return v+"%";}}/><Tooltip content={<TT/>}/><ReferenceLine y={0} stroke={C.border} strokeWidth={2}/><Bar dataKey="ret" name="Return (%)" fill={C.blue} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>)}
            {tab==="weekly"&&(<div style={{background:C.card,border:"1px solid "+C.border,borderRadius:16,overflow:"hidden"}}><div style={{padding:"18px 22px",borderBottom:"1px solid "+C.border,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{fontSize:14,fontWeight:700,color:C.text}}>Weekly Price Forecast</div><div style={{fontSize:11,color:C.sub}}>Next 5 trading days · ARIMA + Ridge</div></div><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr style={{background:C.bg}}>{["Date","CBOT (¢/bu)","ARG (EGP)","BRZ (EGP)"].map(function(h){return <th key={h} style={{padding:"12px 22px",textAlign:"left",color:C.sub,fontWeight:600,fontSize:11,textTransform:"uppercase",letterSpacing:"0.08em"}}>{h}</th>;})}</tr></thead><tbody>{weekly.length===0?(<tr><td colSpan="4" style={{padding:"28px",textAlign:"center",color:C.sub}}>No forecast data</td></tr>):weekly.map(function(row,i){return(<tr key={i} style={{borderTop:"1px solid "+C.border,background:i===0?"rgba(79,142,247,0.05)":"transparent"}}><td style={{padding:"14px 22px",color:i===0?C.blue:C.text,fontWeight:i===0?700:500}}>{row.forecast_date}</td><td style={{padding:"14px 22px",color:C.blue,fontWeight:700}}>{row.cbot_forecast?Number(row.cbot_forecast).toFixed(2):"—"}</td><td style={{padding:"14px 22px",color:C.green,fontWeight:700}}>{row.arg_forecast?Math.round(row.arg_forecast).toLocaleString():"—"}</td><td style={{padding:"14px 22px",color:C.amber,fontWeight:700}}>{row.brz_forecast?Math.round(row.brz_forecast).toLocaleString():"—"}</td></tr>);})}</tbody></table></div>)}
            {tab==="news"&&(
              <div style={{background:C.card,border:"1px solid "+C.border,borderRadius:16,overflow:"hidden"}}>
                <div style={{padding:"18px 22px",borderBottom:"1px solid "+C.border,display:"flex",justifyContent:"space-between",alignItems:"center"}}>
                  <div style={{fontSize:14,fontWeight:700,color:C.text}}>Market News</div>
                  <button onClick={loadNews} style={{padding:"6px 14px",borderRadius:8,border:"1px solid "+C.border,background:"transparent",color:C.sub,fontSize:11,cursor:"pointer",fontWeight:600}}>{newsLoad?"Loading...":"Refresh"}</button>
                </div>
                {newsLoad?(
                  <div style={{padding:"24px",textAlign:"center",color:C.sub}}>Loading news...</div>
                ):news.length===0?(
                  <div style={{padding:"24px",textAlign:"center",color:C.sub}}>No news available</div>
                ):(
                  <div>
                    {news.map(function(item,i){
                      var date = new Date(item.pubDate).toLocaleDateString();
                      return(
                        <a key={i} href={item.link} target="_blank" rel="noreferrer" style={{display:"block",padding:"16px 22px",borderTop:i===0?"none":"1px solid "+C.border,textDecoration:"none",background:i%2===0?"transparent":C.bg+"80",transition:"background 0.2s"}}>
                          <div style={{fontSize:13,fontWeight:600,color:C.text,marginBottom:4,lineHeight:1.4}}>{item.title}</div>
                          <div style={{display:"flex",gap:12,fontSize:11,color:C.sub}}>
                            <span>{item.source||"News"}</span>
                            <span>{date}</span>
                          </div>
                        </a>
                      );
                    })}
                  </div>
                )}
              </div>
            )}
            {tab==="table"&&(<div style={{background:C.card,border:"1px solid "+C.border,borderRadius:16,overflow:"hidden"}}><div style={{padding:"18px 22px",borderBottom:"1px solid "+C.border,fontSize:14,fontWeight:700,color:C.text}}>Raw Data — {data.length} records</div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{background:C.bg}}>{["Date","Close","Low","High","USD Rate",isWheat?"11.5%":"ARG",isWheat?"12.5%":"BRZ","Return"].map(function(h){return <th key={h} style={{padding:"11px 18px",textAlign:"left",color:C.sub,fontWeight:600,fontSize:11,textTransform:"uppercase",letterSpacing:"0.08em",whiteSpace:"nowrap"}}>{h}</th>;})}</tr></thead><tbody>{data.map(function(row,i){var rc=row.fut_ret>0?C.green:row.fut_ret<0?C.red:C.sub;return(<tr key={i} style={{borderTop:"1px solid "+C.border,background:i===0?"rgba(79,142,247,0.05)":"transparent"}}><td style={{padding:"10px 18px",color:i===0?C.blue:C.sub,fontWeight:i===0?700:400}}>{row.date}</td><td style={{padding:"10px 18px",color:C.text,fontWeight:700}}>{fmt(row.closing_cbot)}</td><td style={{padding:"10px 18px",color:C.sub}}>{fmt(row.cbot_low)}</td><td style={{padding:"10px 18px",color:C.sub}}>{fmt(row.cbot_high)}</td><td style={{padding:"10px 18px",color:C.sub}}>{fmt(row.dollar_rate)}</td><td style={{padding:"10px 18px",color:C.green,fontWeight:600}}>{Math.round(row.arg_price).toLocaleString()}</td><td style={{padding:"10px 18px",color:C.amber,fontWeight:600}}>{Math.round(row.brz_price).toLocaleString()}</td><td style={{padding:"10px 18px",color:rc,fontWeight:600}}>{fmt(row.fut_ret*100,2)}%</td></tr>);})}</tbody></table></div></div>)}
          </div>
        )}
      </div>
    </div>
  );
}